import {mkdir, rm, copyFile, readFile, writeFile, readdir, stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
const root=process.cwd(),out=join(root,'dist'),assets=join(out,'assets');
const film=Buffer.concat(await Promise.all(['001','002'].map(part=>readFile(join(root,`cloudflare/media/nabz-story.${part}`)))));
if(createHash('sha256').update(film).digest('hex')!=='03ed290ab32b98b14580c4669715f91c0237455409265b4317eb41272fffc411')throw new Error('NABZ story film is incomplete or corrupted.');
if(film.length>25*1024*1024)throw new Error('NABZ film exceeds the Cloudflare asset limit.');
await rm(out,{recursive:true,force:true});await mkdir(assets,{recursive:true});
const products=[['phulkari-pixels','Phulkari Pixels',1024,1536],['moire','Moiré in Motion',1023,1537],['jali-air','Jali Air',1003,1568],['body-map','Body Map',1003,1568],['dissolving-oxford','Dissolving Oxford',1003,1568],['fault-line','Fault Line',1003,1568]];
const two=v=>String(v).padStart(2,'0');
const figures=products.map(([file,name,width,height],i)=>`<figure class="product-card" data-product-card data-product-index="${i}" ${i?'hidden':''}><button type="button" data-view-image aria-label="View ${name} details"><img src="/assets/nabz-product-${file}.webp" alt="${name} embroidered shirt shown from the front, in detail, and from the back" width="${width}" height="${height}" loading="lazy" decoding="async"><span class="image-open" aria-hidden="true">+</span></button></figure>`).join('\n');
const selectors=products.map(([file,name],i)=>`<button type="button" data-product-select="${i}" aria-pressed="${i===0}"><img src="/assets/nabz-product-${file}.webp" alt="" width="78" height="70" loading="lazy"><span>${two(i+1)}</span><b>${name}</b><i aria-hidden="true"></i></button>`).join('\n');
const source=await readFile(join(root,'sections/nabz-clean-home.liquid'),'utf8');
const svg=source.match(/<svg viewBox="0 0 460 390"[\s\S]*?<\/svg>/)?.[0];
if(!svg)throw new Error('The original NABZ fit illustration is missing.');
const oldRuntime=await readFile(join(root,'assets/nabz-clean-home.js'),'utf8');
const fitStart=oldRuntime.indexOf('  const bootFitSelector ='),fitEnd=oldRuntime.indexOf('  const bootChapterDeck =');
if(fitStart<0||fitEnd<fitStart)throw new Error('The verified fit calculation is missing.');
const fitRuntime=`(() => {\nconst reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;\nconst formatLength=value=>Number(value).toString()+'"';\n${oldRuntime.slice(fitStart,fitEnd)}\nbootFitSelector(document);\n})();\n`;
const script=fitRuntime+await readFile(join(root,'cloudflare/nabz-atelier.js'),'utf8');
const css=await readFile(join(root,'cloudflare/nabz-atelier.css'),'utf8'),template=await readFile(join(root,'cloudflare/atelier.html'),'utf8');
const version=createHash('sha256').update(template+css+script).digest('hex').slice(0,12);
const html=template.replace('__FIGURES__',figures).replace('__SELECTORS__',selectors).replace('__FIT_SVG__',svg.replace('fill="#b58b50"','fill="#884638"')).replaceAll('__VERSION__',version);
if(/{[{%]|__[A-Z_]+__/.test(html))throw new Error('Unresolved content remains in the standalone page.');
if((html.match(/data-product-card/g)||[]).length!==6||(html.match(/data-product-select=/g)||[]).length!==6)throw new Error('All six textile studies must render.');
for(const name of await readdir(join(root,'assets')))if(name.startsWith('nabz-')&&/\.(webp|png)$/.test(name))await copyFile(join(root,'assets',name),join(assets,name));
for(const name of ['cormorant','cormorant-italic','manrope'])await copyFile(join(root,`cloudflare/fonts/${name}.woff2`),join(assets,`nabz-${name}.woff2`));
await copyFile(join(root,'cloudflare/fonts/Cormorant-OFL.txt'),join(assets,'nabz-cormorant-license.txt'));await copyFile(join(root,'cloudflare/fonts/Manrope-OFL.txt'),join(assets,'nabz-manrope-license.txt'));
await writeFile(join(assets,'nabz-atelier.js'),script);await writeFile(join(assets,'nabz-atelier.css'),css);await writeFile(join(assets,'nabz-story.mp4'),film);await writeFile(join(out,'index.html'),html);
await writeFile(join(out,'robots.txt'),'User-agent: *\nAllow: /\n');
await writeFile(join(out,'_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n\n/assets/*\n  Cache-Control: public, max-age=3600, must-revalidate\n');
for(const match of html.matchAll(/(?:src|href|poster)="(\/assets\/[^"?]+)(?:\?[^" ]*)?"/g))await stat(join(out,match[1]));
console.log(`NABZ atelier build complete (${version}). Six studies, self-hosted fonts, exact fit data and original film verified.`);
