import {chromium,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const base=process.env.NABZ_TEST_URL||'http://127.0.0.1:4173';
const browser=await chromium.launch({channel:'chrome',headless:true});
const views=[['desktop',1600,1000],['laptop',1366,768],['wide',1920,1080],['tablet',820,1180],['tablet-landscape',1024,768],['mobile',390,844],['small-mobile',375,667],['android',360,800],['narrow',320,568],['landscape',844,390]];
for(const [name,width,height]of views){
  const page=await browser.newPage({viewport:{width,height},hasTouch:width<=960,isMobile:width<=700});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.url().startsWith(base+'/assets/')&&r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
  await page.goto(base,{waitUntil:'domcontentloaded'});
  await page.evaluate(()=>document.fonts.ready);
  await expect(page.locator('h1')).toBeVisible();
  await expect(page.locator('[data-chapter]')).toHaveCount(5);
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
  await expect(page.locator('.portrait img')).toBeVisible();
  await expect.poll(()=>page.locator('.portrait img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);
  await expect.poll(()=>page.locator('.macro img').evaluate(i=>Math.abs(i.clientHeight/i.clientWidth-1))).toBeLessThan(.02);
  await page.screenshot({path:`nabz-${name}-hero.png`});
  const navigate=async id=>{
    if(id==='hero')await page.getByRole('link',{name:'NABZ home'}).click();
    else await page.locator(`${width>700?'.header-nav':'.chapter-nav'} a[href="#${id}"]`).click();
    await expect.poll(()=>page.locator(`.chapter-nav a[href="#${id}"]`).getAttribute('aria-current')).toBe('location');
    await expect.poll(()=>page.locator('#'+id).evaluate(e=>Math.abs(e.getBoundingClientRect().top-document.querySelector('.site-header').offsetHeight))).toBeLessThan(3);
    const reveals=page.locator('#'+id+' [data-reveal]');
    if(await reveals.count())await expect(reveals.first()).toHaveCSS('opacity','1');
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
  };
  await navigate('products');
  await expect(page.locator('[data-product-card]')).toHaveCount(6);
  await expect(page.locator('[data-product-select]')).toHaveCount(6);
  for(let i=0;i<6;i++){
    await page.locator(`[data-product-select="${i}"]`).click();
    await expect(page.locator(`[data-product-select="${i}"]`)).toHaveAttribute('aria-pressed','true');
    await expect(page.locator('[data-product-card]:visible')).toHaveCount(1);
    await expect.poll(()=>page.locator(`[data-product-index="${i}"] img`).evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
  }
  await page.locator('.gallery').scrollIntoViewIfNeeded();
  await expect(page.locator('.gallery')).toHaveCSS('opacity','1');
  await page.screenshot({path:`nabz-${name}-surface.png`});
  await page.locator('#products').screenshot({path:`nabz-${name}-surface-full.png`,style:'.site-header,.chapter-nav,.skip-link{visibility:hidden}'});
  await page.getByRole('button',{name:'View Fault Line details'}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.locator('#viewer-title')).toHaveText('Fault Line');
  await page.getByRole('button',{name:'Next study',exact:true}).click();
  await expect(page.locator('#viewer-title')).toHaveText('Phulkari Pixels');
  await expect.poll(()=>page.locator('.viewer-image img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);
  await page.screenshot({path:`nabz-${name}-viewer.png`});
  await page.getByRole('button',{name:'Close image viewer'}).press('Escape');
  await expect(page.getByRole('dialog')).toBeHidden();
  await expect(page.locator('[data-product-index="0"] button')).toBeFocused();
  await navigate('fit');
  await page.getByRole('tab',{name:'The system',exact:true}).click();
  await expect(page.locator('#fit-system')).toBeVisible();
  await expect(page.locator('#fit-problem')).toBeHidden();
  await page.getByRole('tab',{name:'The system',exact:true}).press('ArrowLeft');
  await expect(page.getByRole('tab',{name:'The problem',exact:true})).toBeFocused();
  await expect(page.locator('#fit-problem')).toBeVisible();
  await page.getByRole('tab',{name:'The system',exact:true}).click();
  await page.locator('[data-size="L"]').click();await page.locator('[data-length="Extended"]').click();
  await expect(page.locator('[data-fit-output]')).toHaveText('L · Extended · 29.25"');
  await page.locator('[data-size="S"]').click();
  await expect(page.locator('[data-length="Extended"]')).toBeDisabled();
  await expect(page.locator('[data-fit-output]')).toHaveText('S · Standard · 26.75"');
  await expect(page.locator('[data-fit-table-body] tr')).toHaveCount(4);
  await page.locator('.fit-instrument').scrollIntoViewIfNeeded();
  await expect(page.locator('.fit-instrument')).toHaveCSS('opacity','1');
  await page.screenshot({path:`nabz-${name}-fit.png`});
  await page.locator('#fit').screenshot({path:`nabz-${name}-fit-full.png`,style:'.site-header,.chapter-nav,.skip-link{visibility:hidden}'});
  await navigate('story');
  await page.locator('.film').scrollIntoViewIfNeeded();
  await expect(page.locator('.film')).toHaveCSS('opacity','1');
  await page.screenshot({path:`nabz-${name}-story.png`});
  await page.locator('#story').screenshot({path:`nabz-${name}-story-full.png`,style:'.site-header,.chapter-nav,.skip-link{visibility:hidden}'});
  const video=page.locator('video');
  await expect.poll(()=>video.evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(1);
  await page.getByRole('button',{name:'Play NABZ brand film'}).click();
  await expect.poll(()=>video.evaluate(v=>v.currentTime)).toBeGreaterThan(.2);
  await expect(page.locator('[data-story-play]')).toBeHidden();
  await navigate('contact');
  await expect.poll(()=>video.evaluate(v=>v.paused)).toBe(true);
  await expect(page.locator('.contact-card form,.contact-card button')).toHaveCount(0);
  await expect(page.locator('.contact-unavailable')).toContainText('paused');
  await page.locator('.contact-card').scrollIntoViewIfNeeded();
  await expect(page.locator('.contact-card')).toHaveCSS('opacity','1');
  await page.screenshot({path:`nabz-${name}-contact.png`});
  await page.locator('.closing').scrollIntoViewIfNeeded();
  await expect(page.locator('.closing')).toHaveCSS('opacity','1');
  await page.locator('#contact').screenshot({path:`nabz-${name}-contact-full.png`,style:'.site-header,.chapter-nav,.skip-link{visibility:hidden}'});
  await navigate('hero');
  if(errors.length)throw new Error(`${name}: ${errors.join('; ')}`);
  console.log(`${name}: fonts, layout, all six products, image viewer, exact fit, film playback and chapter navigation passed`);
  await page.close();
}
const reduced=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
await reduced.goto(base,{waitUntil:'domcontentloaded'});
await reduced.evaluate(()=>document.fonts.ready);
await expect.poll(()=>reduced.locator('.portrait img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);
await expect(reduced.locator('html')).not.toHaveClass(/is-enhanced/);
await expect(reduced.locator('.surface-copy')).toHaveCSS('opacity','1');
await reduced.screenshot({path:'nabz-reduced-motion.png'});
await reduced.close();
const fallback=await browser.newPage({viewport:{width:390,height:844},javaScriptEnabled:false});
await fallback.goto(base,{waitUntil:'domcontentloaded'});
await fallback.evaluate(()=>document.fonts.ready);
await expect(fallback.locator('h1')).toBeVisible();
await expect(fallback.locator('video')).toHaveAttribute('controls','');
await expect(fallback.locator('[data-story-play]')).toBeHidden();
await expect(fallback.locator('.story-heading')).toHaveCSS('opacity','1');
await fallback.close();
await browser.close();
console.log('NABZ atelier browser checks passed.');
